# Generated by Django 2.1.1 on 2018-10-23 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(max_length=100)),
                ('blog_detail', models.CharField(max_length=300)),
                ('blog_content', models.TextField()),
                ('blog_date', models.DateTimeField(auto_now_add=True)),
                ('blog_readnum', models.IntegerField(default=0)),
                ('blog_zan', models.IntegerField(default=0)),
                ('blog_image', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'blog',
                'ordering': ['-blog_date'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_name', models.CharField(max_length=100)),
                ('cate_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'category',
                'ordering': ['-cate_date'],
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_cate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Category'),
        ),
    ]
