# Generated by Django 2.1.1 on 2018-10-29 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_blog_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags_Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_time', models.CharField(default='2018年10', max_length=100)),
            ],
            options={
                'db_table': 'tags',
                'ordering': ['-tag_time'],
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_tage_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Tags_Time'),
        ),
    ]
