# Generated by Django 2.1.1 on 2018-10-29 10:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181029_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags_time',
            name='tag_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tags_time',
            name='tag_time',
            field=models.CharField(default='2018年10月', max_length=100),
        ),
    ]
